app1/urls.py
from django.urls import path
from app1.views import *
app_name="app1"
urlpatterns=[
    path('app1_noo/',app1_noo,name='app1_noo'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name="app2"
urlpatterns=[
    path('app2_hin',app2_hin,name='app2_hin'),
]

specificfolder_navigation/urls.py
from django.contrib import admin
from django.urls import path,include
import app1
import app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def app1_noo(request):
    return render(request,'app1/app_hai.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def app2_hin(request):
    return render(request,'app2/app_bye.html')

templates/app1/app_hai.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>specific folder1</h1>
        <h4><a href="{% url 'app2:app2_hin' %}">go to secound page</a></h4>
    </center>
</body>
</html>

templates/app2/app_bye.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>specific folder2</h1>
        <h4><a href="{% url 'app1:app1_noo' %}">go to first page</a></h4>
    </center>
</body>
</html>